apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379        # listen on 
      targetPort: 6379  # forwards to
  selector:   # we use the labels we used when creating PODs
    name: redis-pod
    app: demo-voting-app