apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer # this exposes the load balancer externally
  ports:
    - port: 80        # listen on 
      targetPort: 80  # forwards to
  selector:   # we use the labels we used when creating PODs
    name: result-app-pod
    app: demo-voting-app